pymmcore-plus/pymmcore-gui

- .github/workflows/bundle.yml
- .github/workflows/ci.yml
- pyproject.toml
- uv.lock
this PR would switch to using pymmcore-nano for the gui.  nano is likely to be *slightly* faster, with lower latencies, and possibly better buffer handling (due to nanobind's efficiency over SWIG).
> build: use pymmcore-nano instead

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/pymmcore_gui/_app.py
- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/actions/widget_actions.py
- src/pymmcore_gui/widgets/_exception_log.py
- src/pymmcore_gui/widgets/_mm_console.py
- src/pymmcore_gui/widgets/_stage_control.py
- src/pymmcore_gui/widgets/_toolbars.py
- uv.lock
though mypy is community "standard".  pyright is a great type checker.  often faster with more configurability.  
This sets up pyright as an additional option and runs it manually in `ci.yml` (but not in pre-commit.ci due to environment creation limits).  That does mean we're "duplicating" type checking. and could conceivably remove the mypy-section from pre-commit (since it's quite ugly and verbose).  But i'm not doing that here yet either, because pre-commit is nice to run locally.  it's a long story :joy:, anyone please feel free to ask if you'd like to know more
> chore: more type stability, setup pyright as alternative option to mypy

- .pre-commit-config.yaml
- pyproject.toml
- src/pymmcore_gui/widgets/_toolbars.py
- uv.lock
I had been using pymmcore-nano, mostly as a way to dogfood the new experiment.  But it looks like there are some threading issues that are somewhat serious in the context of a gui application.  (https://github.com/pymmcore-plus/pymmcore-nano/issues/32).  So this disables pymmcore nano until those are resolved
> build: use regular pymmcore instead of pymmcore-nano

- src/pymmcore_gui/actions/widget_actions.py
- uv.lock
This PR removes `wdg.setMaximumHeight(140)` from the `CameraRoiWidget`, as it was causing the widget to be clipped.
> fix: remove setMaximumHeight

- README.md
this adds the links to the bundled "nightly" app to the readme
> docs: add link to latest bundles in readme

- .github/workflows/bundle.yml
- .github/workflows/ci.yml
@fdrgsp , I this will solve the uv.lock issues you're seeing in #19 
according to https://docs.astral.sh/uv/concepts/projects/sync/#checking-if-the-lockfile-is-up-to-date:
> To avoid updating the lockfile during uv sync and uv run invocations, use the --frozen flag.
>
> To assert the lockfile matches the project metadata, use the --locked flag. If the lockfile is not up-to-date, an error will be raised instead of updating the lockfile.
all we really want to do is ensure that the lock file doesn't update while running tests.  I don't think we need to assert that it *wouldn't*, since that might be a bit more specific to the uv version.  I still don't have an answer as to why/when the lockfile is getting changed (when pyproject hasn't been touched).
> build: use UV_FROZEN not UV_LOCKED

- .pre-commit-config.yaml
- pyproject.toml
- src/pymmcore_gui/_app.py
- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/actions/widget_actions.py
- src/pymmcore_gui/widgets/_image_preview.py
- src/pymmcore_gui/widgets/_pygfx_image.py
- src/pymmcore_gui/widgets/_toolbars.py
- tests/conftest.py
- tests/test_widgets.py
- uv.lock
I think I'd like to base all graphics here on pygfx, instead of vispy.  It's more modern, cleaner with respect to qt implementation (less leaked references around and less segfaults in testing).
This adds a fast `ImagePreview` variant to the vispy one in pymmcore-widgets.   I do want to use ndv ultimately, but also don't mind having a few strict performance-optimized things here too
> feat: add `PygfxImagePreview` widget, use pygfx instead of vispy

- src/pymmcore_gui/_main_window.py
- tests/test_main_window.py
Calling `MicroManagerGui.get_widget()` may sometimes return a QDockWidget, and sometimes the inner widget... which is confusing.  This makes it that `get_widget` *always* returns the expected actual widget, and adds manual overloads to make the typing work out correctly so that you know exactly what widget type you're dealing with.  Also adds a `get_dock_widget` method in the case where you actually want the dock widget itself
> fix: Make `get_widget` always return the inner widget

- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/widgets/_mm_console.py
- tests/test_main_window.py
fixes #36 by ensuring that all widgets created using `get_widget` are long-lived singletons that simply get hidden instead of closed.  This has potential resource implications, since these widgets will only ever be hidden and not cleaned up ... but let's deal with that if it becomes an issues
> fix: fix hide/show of dock widget singletons

- src/pymmcore_gui/_app.py
- tests/conftest.py
- tests/test_app.py
fixes a test failing we're seeing in #41 
it's an odd failure, caused by the app going out of scope too quickly
> fix: fix tests by retaining app pointer

- src/pymmcore_gui/widgets/_toolbars.py
- tests/test_main_window.py
We have an issue with the shutter widget toolbar when loading a new configuration. If a shutter with the same name does not exist in the new configuration, we get shutter widgets with `None`.
This PR clears the shutter toolbar before updating it with the new shutter devices.
---
> fix: fix shutter toolbar when loading a new configuration

- src/pymmcore_gui/_app.py
in some of my reversions before merging #38, I accidentally added back the `.showMaximized()` call in `main()`.  This removes it
> fix: remove showMaximized from main()

- src/pymmcore_gui/widgets/_toolbars.py
The OCToolBar widget should also listen to propertyChanged signal when the "Core" "ChannelGroup" is changed (e.g `mmc.setProperty("Core", "ChannelGroup", "Channel"`)
> fix: the OCToolBar widget should listen to propertyChanged 

- src/pymmcore_gui/_app.py
- tests/test_app.py
this removes a weird hack that I didn't understand in the first place, and appears to be no longer needed
> refactor: remove _app.main() return value

- .pre-commit-config.yaml
- PRIVACY.md
- codecov.yml
- pyproject.toml
- src/pymmcore_gui/_app.py
- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/_sentry.py
- src/pymmcore_gui/_settings.py
- src/pymmcore_gui/widgets/_exception_log.py
- tests/conftest.py
- tests/test_main_window.py
- tests/test_settings.py
- uv.lock
This adds opt-in error reporting via sentry.io
If a user hasn't made a choice, they are presented with this dialog:
and can later opt in/out via the exceptions log:
on sentry, this is what we see:
> feat: add auto-error reporting via sentry

- pyproject.toml
- src/pymmcore_gui/__init__.py
- src/pymmcore_gui/__main__.py
- src/pymmcore_gui/_app.py
- src/pymmcore_gui/_main_window.py
- tests/test_app.py
- uv.lock
The primary feature of this PR is the new `pymmcore_gui.create_mmgui` function.  It's intended use is for someone who wants to spin up pymmcore_gui's main window, with all of the standard features (including except hook patches, and settings etc...), but still do something before the application starts.  I imagine it being useful for scenarios like https://github.com/pymmcore-plus/pymmcore-gui/issues/34 ... and a general step towards extensibility
pretty much all the remaining changes are just moving code around, and updating the lockfile (to pyqt6 6.9)
> feat: Add public `create_mmgui` function

- .gitignore
- pyproject.toml
- src/pymmcore_gui/_app.py
- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/_settings.py
- src/pymmcore_gui/actions/__init__.py
- src/pymmcore_gui/actions/_action_info.py
- src/pymmcore_gui/actions/_core_qaction.py
- src/pymmcore_gui/actions/core_actions.py
- src/pymmcore_gui/actions/widget_actions.py
- src/pymmcore_gui/widgets/_notifications.py
- tests/test_actions.py
- tests/test_app.py
- tests/test_main_window.py
- uv.lock
This PR would enable end-users to contribute widgets or other CoreActions to the gui by creating an instance of `WidgetActionInfo` prior to MainWindow creation.  For example:
```python
from pymmcore_gui import create_mmgui
from pymmcore_gui.actions import WidgetActionInfo
from PyQt6.QtWidgets import QWidget
def create_my_widget(parent: QWidget) -> QWidget:
wdg = QWidget(parent)
wdg.setStyleSheet("background-color: lightblue;")
return wdg
WidgetActionInfo(
key="mywidget",
text="My Widget!!!!",
icon="mdi-light:format-list-bulleted",
create_widget=create_my_widget,
)
create_mmgui()
```
This is a step towards extensibility of the GUI
> feat: Enable contribution of widgets and (other actions) by declaring `[Widget]ActionInfo`

- src/pymmcore_gui/actions/_core_qaction.py
Now they can be seen with a dark theme!
For reference, here's how it looked before:
> feat: set icons to text color

- src/pymmcore_gui/actions/_core_qaction.py
I have been working on a couple dedicated widgets for Becker & Hickl devices. I want Becker & Hickl / B&H to appear in the WidgetActionInfo text.
Since we already have the shortcut field on WidgetActionInfo, I think it's best to disable shortcuts within the QAction text by escaping the ampersands.
> fix: QCoreAction: avoid QAction mnemonics

- src/pymmcore_gui/actions/core_actions.py
I kept trying to press Snap/Live without remembering to load a config file. This PR disables those buttons if you don't have a camera.
This is something that we do with the Snap Button and Live Button in pymmcore-widgets. Ideally, we'd just use those buttons, but since we aren't doing that now, this change solves the problem.
> fix: Disable Snap/Live when camera unavailable

- src/pymmcore_gui/_main_window.py
- src/pymmcore_gui/actions/widget_actions.py
We need an intuitive way to load and save configuration files. Right now, the only option provided by the GUI is the buttons on the GroupPresetTableWidget, which might not be open.
This PR provides a solution using a new Menu (titled "Device"), aligning with the existing mmstudio solution. It also moves the Hardware Configuration Wizard into this menu.
> feat: device menu

- src/pymmcore_gui/__init__.py
Before importing any third-party packages, load these DLLs from the system-installed copies (or copies bundled by the Python interpreter in the case of `vcruntime140[_1].dll`).
Closes #91.
Another way to do this would be to put this code in pymmcore-plus (where we can document that it needs to be imported before certain packages such as PyQt), and import pymmcore_plus before everything else.
Some additional details:
Currently, pymmcore and Micro-Manager device adapters use concrt140, msvcp140, vcruntime140, and vcruntime140_1. The Micro-Manager installer installs vc_redist 14.42.34438.0 at the moment.
As mentioned in the comment, CPython bundles vcruntime140 and vcruntime140_1. Python.org Python 3.12.10 and 3.13.5 bundle 14.42.34438.0; 3.11.9 bundles 14.38.33126; and 3.9.13 and 3.10.11 …
> fix: pre-load MSVC DLLs to block old versions
